name: whw_gridded_data
channels:
  - conda-forge
dependencies:
  - python=3.6
  - ipython
  - ipykernel
  - geopandas
  - matplotlib
  - cartopy
  - seaborn
  - xarray
  - rasterio
  - dask
  - boto3
